name: Test and Deploy Lib and FastAPI Service

on:
  push: # sÃ³ realiza o workflow quando houver push nessas branches
    branches:
      - main
      - master 

permissions:
  contents: read
  packages: write

jobs: # definiÃ§Ã£o dos jobs (tarefas) que serÃ£o executadas no workflow
  test-lib:
    name: ðŸ§ª Test Hero Lib
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build and test tools
        run: | # instala as dependÃªncias necessÃ¡rias para build e teste
          python -m pip install --upgrade pip 
          python -m pip install build twine pytest
          pip install -r requirements.txt

      - name: Install lib locally
        run: |
          python -m pip install .

      - name: Run tests for library
        run: |
          pytest tests/
  
  deploy-lib:
    name: ðŸ“¦ Publish Hero Lib to PyPI
    runs-on: ubuntu-latest
    needs: test-lib

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build library
        run: |
          python -m build
      
      - name: Publish library to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          twine upload dist/*